skillcodes:
  mappings:
    app1:
      balance: 
        screen1: 123
        screen2: 234
        screen3: 676
      transfer:
        screen1: 679
        screen2: 778
        screen3: 7888
      account: 
        screen1: 689
        screen2: 678
        screen3: 778
    app2:
      enquiry:
        screen1: 7678
        screen2: 880
    app3:
      default:
        screen1: 688678
